name: deploy-open-bridge-staging

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      branch: ${{ github.ref_name }}
      destination_bucket: staging-studies-bridgedigital-healt-websitebucket-llv54doyeqrl
      distribution_id: E3S5F61K1105VI